"""add userextension

Revision ID: 87168d0c866c
Revises: 0a8dacd2c9e9
Create Date: 2025-07-06 21:31:37.291034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87168d0c866c'
down_revision: Union[str, None] = '0a8dacd2c9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_extensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('university', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_extensions_id'), 'user_extensions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extensions_id'), table_name='user_extensions')
    op.drop_table('user_extensions')
    # ### end Alembic commands ###
